[workspace]

members = [
    "mobile_ffi",
    "uniffi-bindgen",
]
resolver = "2"

[profile.release]
lto = true
opt-level = "s"
#strip = true
debug = true
codegen-units = 1


[workspace.dependencies]
uniffi = "0.28.0"
